name       : abseil-cpp
version    : '20210324.2'
release    : 1
source     :
    - https://github.com/abseil/abseil-cpp/archive/refs/tags/20210324.2.tar.gz : 59b862f50e710277f8ede96f083a5bb8d7c9595376146838b9580be90374ee1f
homepage   : https://abseil.io/
license    : Apache-2.0
component  : programming.library
summary    : Abseil Common Libraries
description: |
    Collection of C++ library code designed to augment the C++ standard library.
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_CXX_STANDARD=17 \
        -DABSL_CXX_STANDARD=17
build      : |
    %ninja_build
install    : |
    %ninja_install
